// nuxt/pages/privacy.vue
<template>
  <div class="noise-bg grid-bg min-h-screen">
    <Navbar />
    <main class="relative z-10 mx-auto max-w-3xl px-6 py-16">
      <PageHeader>
        <template #title>>> PRIVACY POLICY</template>
        <template #description>
          Last updated: December 25, 2025
        </template>
      </PageHeader>

      <div class="space-y-8 text-muted-foreground">
        <section>
          <h2 class="mb-4 text-lg font-semibold text-foreground">1. Information We Collect</h2>
          <p class="mb-4">We collect information you provide directly to us:</p>
          <ul class="list-inside list-disc space-y-2">
            <li>Account information (email, name)</li>
            <li>Payment information (processed by Paddle)</li>
            <li>Usage data and API logs</li>
          </ul>
        </section>

        <section>
          <h2 class="mb-4 text-lg font-semibold text-foreground">2. How We Use Your Information</h2>
          <ul class="list-inside list-disc space-y-2">
            <li>To provide and maintain our services</li>
            <li>To process payments and send invoices</li>
            <li>To communicate with you about your account</li>
            <li>To improve our services</li>
          </ul>
        </section>

        <section>
          <h2 class="mb-4 text-lg font-semibold text-foreground">3. Data Processing</h2>
          <p>
            Data submitted to our APIs is processed in real-time and is not stored permanently unless explicitly required for the service (e.g., batch processing). We do not use your data to train AI models.
          </p>
        </section>

        <section>
          <h2 class="mb-4 text-lg font-semibold text-foreground">4. Data Security</h2>
          <p>
            We implement industry-standard security measures to protect your data, including encryption in transit and at rest, and regular security audits.
          </p>
        </section>

        <section>
          <h2 class="mb-4 text-lg font-semibold text-foreground">5. Third-Party Services</h2>
          <p>
            We use third-party services for payment processing (Paddle), analytics, and infrastructure. These services have their own privacy policies.
          </p>
        </section>

        <section>
          <h2 class="mb-4 text-lg font-semibold text-foreground">6. Your Rights</h2>
          <p>You have the right to:</p>
          <ul class="mt-2 list-inside list-disc space-y-2">
            <li>Access your personal data</li>
            <li>Request correction or deletion of your data</li>
            <li>Export your data</li>
            <li>Opt out of marketing communications</li>
          </ul>
        </section>

        <section>
          <h2 class="mb-4 text-lg font-semibold text-foreground">7. Contact</h2>
          <p>
            For privacy-related inquiries, contact us at:
            <a href="mailto:support@kikuai.dev" class="text-primary hover:underline">support@kikuai.dev</a>
          </p>
        </section>
      </div>
    </main>
    <Footer />
  </div>
</template>

// app/privacy/page.tsx
"use client"

import { motion } from "framer-motion"
import { Navbar } from "@/components/navbar"
import { Footer } from "@/components/footer"

export default function PrivacyPage() {
  return (
    <div className="relative min-h-screen bg-background text-foreground">
      <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-primary/5 via-transparent to-transparent" />
      <div
        className="pointer-events-none absolute inset-0 opacity-[0.015]"
        style={{
          backgroundImage: `url("data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noise'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noise)'/%3E%3C/svg%3E")`,
        }}
      />

      <Navbar />

      <main className="relative z-10 mx-auto max-w-3xl px-6 py-24">
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5 }}>
          <p className="mb-4 text-sm text-muted-foreground">Last updated: December 2024</p>
          <h1 className="mb-8 text-4xl font-semibold tracking-tight">Privacy Policy</h1>

          <div className="space-y-6 text-muted-foreground">
            <section>
              <h2 className="mb-3 text-lg font-medium text-foreground">Data We Collect</h2>
              <p>We collect minimal data necessary to provide our services:</p>
              <ul className="mt-2 list-inside list-disc space-y-1">
                <li>Account information (email, name)</li>
                <li>Payment information (processed by Stripe)</li>
                <li>Usage logs (API calls, timestamps)</li>
              </ul>
            </section>

            <section>
              <h2 className="mb-3 text-lg font-medium text-foreground">Data Processing</h2>
              <p>
                Input data sent to our APIs (images, text) is processed in real-time and immediately discarded after
                generating outputs. We do not store your input data or use it for training models.
              </p>
            </section>

            <section>
              <h2 className="mb-3 text-lg font-medium text-foreground">Data Sharing</h2>
              <p>We do not sell your data. We may share data with third-party services necessary for operations:</p>
              <ul className="mt-2 list-inside list-disc space-y-1">
                <li>Stripe for payment processing</li>
                <li>Cloud providers for infrastructure</li>
                <li>Analytics tools (anonymized usage data only)</li>
              </ul>
            </section>

            <section>
              <h2 className="mb-3 text-lg font-medium text-foreground">Cookies</h2>
              <p>
                We use essential cookies for authentication and session management. No third-party tracking cookies are
                used.
              </p>
            </section>

            <section>
              <h2 className="mb-3 text-lg font-medium text-foreground">Your Rights</h2>
              <p>
                You can request access to, correction of, or deletion of your personal data by contacting{" "}
                <a href="mailto:privacy@kikuai.dev" className="text-primary hover:underline">
                  privacy@kikuai.dev
                </a>
              </p>
            </section>

            <section>
              <h2 className="mb-3 text-lg font-medium text-foreground">Updates</h2>
              <p>We may update this policy periodically. Significant changes will be communicated via email.</p>
            </section>
          </div>
        </motion.div>
      </main>

      <Footer />
    </div>
  )
}
