// nuxt/components/Footer.vue
<template>
  <footer class="relative z-10 border-t border-border/40">
    <div class="mx-auto flex max-w-6xl flex-col items-center justify-between gap-4 px-6 py-8 sm:flex-row">
      <div class="flex flex-wrap items-center gap-6 text-sm text-muted-foreground">
        <NuxtLink to="/products/chart2csv" class="transition-colors hover:text-foreground">
          Chart2CSV
        </NuxtLink>
        <NuxtLink to="/products/patas" class="transition-colors hover:text-foreground">
          PATAS
        </NuxtLink>
        <NuxtLink to="/docs" class="transition-colors hover:text-foreground">
          Docs
        </NuxtLink>
        <NuxtLink to="/pricing" class="transition-colors hover:text-foreground">
          Pricing
        </NuxtLink>
      </div>

      <div class="flex flex-wrap items-center gap-6 text-sm text-muted-foreground">
        <NuxtLink to="/refund" class="transition-colors hover:text-foreground">
          Refund
        </NuxtLink>
        <NuxtLink to="/terms" class="transition-colors hover:text-foreground">
          Terms
        </NuxtLink>
        <NuxtLink to="/privacy" class="transition-colors hover:text-foreground">
          Privacy
        </NuxtLink>
        <NuxtLink to="/open-source" class="transition-colors hover:text-foreground">
          Open Source
        </NuxtLink>
        <a
          href="https://github.com/kikuai"
          target="_blank"
          rel="noopener noreferrer"
          class="transition-colors hover:text-foreground"
        >
          <Github class="h-4 w-4" />
          <span class="sr-only">GitHub</span>
        </a>
      </div>
    </div>

    <div class="border-t border-border/20 py-4 text-center text-xs text-muted-foreground/60">
      © {{ new Date().getFullYear() }} KikuAI. All rights reserved.
    </div>
  </footer>
</template>

<script setup lang="ts">
import { Github } from 'lucide-vue-next'
</script>

// components/footer.tsx
"use client"

import Link from "next/link"
import { motion } from "framer-motion"
import { Github } from "lucide-react"

export function Footer() {
  return (
    <motion.footer
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      transition={{ duration: 0.5, delay: 0.8 }}
      className="relative z-10 border-t border-border/40"
    >
      <div className="mx-auto flex max-w-6xl flex-col items-center justify-between gap-4 px-6 py-8 sm:flex-row">
        <div className="flex flex-wrap items-center justify-center gap-x-6 gap-y-2 text-sm text-muted-foreground">
          <Link href="/products/chart2csv" className="transition-colors hover:text-foreground">
            Chart2CSV
          </Link>
          <Link href="/products/patas" className="transition-colors hover:text-foreground">
            PATAS
          </Link>
          <Link href="/pricing" className="transition-colors hover:text-foreground">
            Pricing
          </Link>
          <Link href="/docs" className="transition-colors hover:text-foreground">
            Docs
          </Link>
          <Link href="/about" className="transition-colors hover:text-foreground">
            About
          </Link>
        </div>

        <div className="flex items-center gap-6 text-sm text-muted-foreground">
          <Link href="/open-source" className="transition-colors hover:text-foreground">
            Open Source
          </Link>
          <a
            href="https://github.com/kikuai"
            target="_blank"
            rel="noopener noreferrer"
            className="transition-colors hover:text-foreground"
          >
            <Github className="h-4 w-4" />
            <span className="sr-only">GitHub</span>
          </a>
        </div>
      </div>

      <div className="border-t border-border/20 py-4">
        <div className="mx-auto flex max-w-6xl flex-col items-center justify-between gap-2 px-6 sm:flex-row">
          <p className="text-xs text-muted-foreground/60">© {new Date().getFullYear()} KikuAI. All rights reserved.</p>
          <div className="flex items-center gap-4 text-xs text-muted-foreground/60">
            <Link href="/refund" className="transition-colors hover:text-muted-foreground">
              Refund Policy
            </Link>
            <Link href="/terms" className="transition-colors hover:text-muted-foreground">
              Terms
            </Link>
            <Link href="/privacy" className="transition-colors hover:text-muted-foreground">
              Privacy
            </Link>
          </div>
        </div>
      </div>
    </motion.footer>
  )
}
