// nuxt/pages/terms.vue
<template>
  <div class="noise-bg grid-bg min-h-screen">
    <Navbar />
    <main class="relative z-10 mx-auto max-w-3xl px-6 py-16">
      <PageHeader>
        <template #title>>> TERMS OF SERVICE</template>
        <template #description>
          Last updated: December 25, 2025
        </template>
      </PageHeader>

      <div class="space-y-8 text-muted-foreground">
        <section>
          <h2 class="mb-4 text-lg font-semibold text-foreground">1. Acceptance of Terms</h2>
          <p>
            By accessing or using KikuAI services, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our services.
          </p>
        </section>

        <section>
          <h2 class="mb-4 text-lg font-semibold text-foreground">2. Service Description</h2>
          <p>
            KikuAI provides API services for data extraction, pattern analysis, PII masking, and API reliability. Services are provided "as is" and may be updated or modified at any time.
          </p>
        </section>

        <section>
          <h2 class="mb-4 text-lg font-semibold text-foreground">3. Account Responsibilities</h2>
          <ul class="list-inside list-disc space-y-2">
            <li>You are responsible for maintaining the security of your API keys</li>
            <li>You must not share your credentials with unauthorized parties</li>
            <li>You are responsible for all activity under your account</li>
          </ul>
        </section>

        <section>
          <h2 class="mb-4 text-lg font-semibold text-foreground">4. Acceptable Use</h2>
          <p>You agree not to use our services to:</p>
          <ul class="mt-2 list-inside list-disc space-y-2">
            <li>Violate any laws or regulations</li>
            <li>Infringe on intellectual property rights</li>
            <li>Transmit malicious code or spam</li>
            <li>Attempt to gain unauthorized access to our systems</li>
          </ul>
        </section>

        <section>
          <h2 class="mb-4 text-lg font-semibold text-foreground">5. Payment Terms</h2>
          <p>
            Payments are processed by Paddle.com as our Merchant of Record. All fees are non-refundable except as specified in our Refund Policy.
          </p>
        </section>

        <section>
          <h2 class="mb-4 text-lg font-semibold text-foreground">6. Limitation of Liability</h2>
          <p>
            KikuAI shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of our services.
          </p>
        </section>

        <section>
          <h2 class="mb-4 text-lg font-semibold text-foreground">7. Contact</h2>
          <p>
            For questions about these terms, contact us at:
            <a href="mailto:support@kikuai.dev" class="text-primary hover:underline">support@kikuai.dev</a>
          </p>
        </section>
      </div>
    </main>
    <Footer />
  </div>
</template>

// app/terms/page.tsx
"use client"

import { motion } from "framer-motion"
import { Navbar } from "@/components/navbar"
import { Footer } from "@/components/footer"

export default function TermsPage() {
  return (
    <div className="relative min-h-screen bg-background text-foreground">
      <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-primary/5 via-transparent to-transparent" />
      <div
        className="pointer-events-none absolute inset-0 opacity-[0.015]"
        style={{
          backgroundImage: `url("data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noise'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noise)'/%3E%3C/svg%3E")`,
        }}
      />

      <Navbar />

      <main className="relative z-10 mx-auto max-w-3xl px-6 py-24">
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5 }}>
          <p className="mb-4 text-sm text-muted-foreground">Last updated: December 2024</p>
          <h1 className="mb-8 text-4xl font-semibold tracking-tight">Terms of Service</h1>

          <div className="space-y-6 text-muted-foreground">
            <section>
              <h2 className="mb-3 text-lg font-medium text-foreground">1. Acceptance of Terms</h2>
              <p>
                By accessing or using KikuAI services, you agree to be bound by these Terms of Service. If you do not
                agree to these terms, do not use our services.
              </p>
            </section>

            <section>
              <h2 className="mb-3 text-lg font-medium text-foreground">2. Service Description</h2>
              <p>
                KikuAI provides AI-powered data extraction and transformation APIs. Services include Chart2CSV, PATAS,
                Masker, and ReliAPI. We reserve the right to modify or discontinue services at any time.
              </p>
            </section>

            <section>
              <h2 className="mb-3 text-lg font-medium text-foreground">3. User Responsibilities</h2>
              <p>You agree to:</p>
              <ul className="mt-2 list-inside list-disc space-y-1">
                <li>Provide accurate account information</li>
                <li>Maintain the security of your API keys</li>
                <li>Use services in compliance with applicable laws</li>
                <li>Not abuse, overload, or attempt to exploit our systems</li>
              </ul>
            </section>

            <section>
              <h2 className="mb-3 text-lg font-medium text-foreground">4. Payment and Balance</h2>
              <p>
                Balance is purchased in advance and deducted upon API usage. Balance never expires. All purchases are
                final unless otherwise specified in our Refund Policy.
              </p>
            </section>

            <section>
              <h2 className="mb-3 text-lg font-medium text-foreground">5. Intellectual Property</h2>
              <p>
                You retain ownership of your input data and outputs. KikuAI retains ownership of the service, APIs, and
                underlying technology.
              </p>
            </section>

            <section>
              <h2 className="mb-3 text-lg font-medium text-foreground">6. Limitation of Liability</h2>
              <p>
                KikuAI is provided "as is" without warranties. We are not liable for indirect, incidental, or
                consequential damages arising from use of our services.
              </p>
            </section>

            <section>
              <h2 className="mb-3 text-lg font-medium text-foreground">7. Contact</h2>
              <p>
                For questions about these terms, contact{" "}
                <a href="mailto:legal@kikuai.dev" className="text-primary hover:underline">
                  legal@kikuai.dev
                </a>
              </p>
            </section>
          </div>
        </motion.div>
      </main>

      <Footer />
    </div>
  )
}
