// nuxt/pages/products/reliapi.vue
<template>
  <div class="noise-bg grid-bg min-h-screen">
    <Navbar />
    <main class="relative z-10 mx-auto max-w-4xl px-6 py-16">
      <PageHeader back-link="/">
        <template #title>ReliAPI</template>
        <template #description>
          Reliability layer for API calls with retries, caching, and circuit breakers
        </template>
      </PageHeader>

      <!-- Action buttons -->
      <div class="mb-12 flex flex-wrap gap-3">
        <NuxtLink
          to="#demo"
          class="inline-flex h-10 items-center justify-center rounded-xl bg-primary px-5 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90"
        >
          Try demo
        </NuxtLink>
        <NuxtLink
          to="/dashboard"
          class="inline-flex h-10 items-center justify-center rounded-xl border border-border bg-card px-5 text-sm font-medium transition-colors hover:bg-secondary"
        >
          Get API key
        </NuxtLink>
        <a
          href="https://github.com/KikuAI-Lab/reliapi/wiki"
          target="_blank"
          class="inline-flex h-10 items-center justify-center rounded-xl border border-border bg-card px-5 text-sm font-medium transition-colors hover:bg-secondary"
        >
          Docs
        </a>
        <a
          href="https://github.com/KikuAI-Lab/reliapi"
          target="_blank"
          class="inline-flex h-10 items-center gap-2 justify-center rounded-xl border border-border bg-card px-5 text-sm font-medium transition-colors hover:bg-secondary"
        >
          <Github class="h-4 w-4" />
          GitHub
        </a>
      </div>

      <!-- Description -->
      <div class="mb-12 space-y-4 text-muted-foreground">
        <p>
          ReliAPI provides automatic retries, response caching, deduplication, and circuit-breaker logic for any HTTP API endpoint.
        </p>
        <p>
          It handles transient failures, reduces load on downstream services, and improves response times through intelligent caching and request deduplication.
        </p>
      </div>

      <!-- Problem / When to use -->
      <div class="mb-12 grid gap-6 md:grid-cols-2">
        <div class="rounded-xl border border-border/60 bg-card p-6">
          <h3 class="mb-3 font-semibold">Problem</h3>
          <p class="text-sm text-muted-foreground">
            External APIs can be unreliable, slow, or rate-limited. Without proper handling, failures cascade and performance degrades.
          </p>
        </div>
        <div class="rounded-xl border border-border/60 bg-card p-6">
          <h3 class="mb-3 font-semibold">When to use</h3>
          <p class="text-sm text-muted-foreground">
            Use ReliAPI when calling external APIs that may be unreliable, slow, or rate-limited. It handles all the retry and caching logic automatically.
          </p>
        </div>
      </div>

      <div class="mb-12 rounded-xl border border-border/60 bg-card p-6">
        <h3 class="mb-4 font-semibold">Input / Output</h3>
        <div class="grid gap-4 sm:grid-cols-2">
          <div>
            <div class="mb-2 text-xs font-medium uppercase tracking-wider text-muted-foreground">Input</div>
            <p class="text-sm">HTTP request to any API endpoint</p>
          </div>
          <div>
            <div class="mb-2 text-xs font-medium uppercase tracking-wider text-muted-foreground">Output</div>
            <p class="text-sm">Cached response if available, or retried request with circuit breaker protection</p>
          </div>
        </div>
      </div>

      <!-- Visual Demo -->
      <div class="mb-12 rounded-xl border border-border/60 bg-card p-6">
        <h3 class="mb-4 font-semibold">How it works</h3>
        <div class="flex flex-wrap items-center gap-4 font-mono text-sm">
          <div class="rounded-lg bg-secondary/50 px-4 py-2">
            <span class="text-muted-foreground">GET /api/data</span>
          </div>
          <ArrowRight class="h-5 w-5 text-primary" />
          <div class="rounded-lg bg-emerald-500/10 px-4 py-2">
            <span class="text-emerald-400">CACHE HIT</span>
            <span class="ml-2 text-muted-foreground/60">2ms</span>
          </div>
        </div>
      </div>

      <!-- Demo Section -->
      <section id="demo" class="scroll-mt-24">
        <h2 class="mb-6 text-xl font-semibold">Try it now</h2>
        <CodeBlock
          :tabs="['cURL', 'JavaScript', 'Python']"
          :code="codeExamples"
        />
      </section>
    </main>
    <Footer />
  </div>
</template>

<script setup lang="ts">
import { Github, ArrowRight } from 'lucide-vue-next'

const codeExamples = {
  cURL: `curl -X POST https://reliapi.kikuai.dev/api/proxy \\
  -H "Content-Type: application/json" \\
  -H "X-Target-URL: https://api.example.com/data" \\
  -d '{"key": "value"}'`,
  JavaScript: `const response = await fetch('https://reliapi.kikuai.dev/api/proxy', {
  method: 'POST',
  headers: {
    'Content-Type': 'application/json',
    'X-Target-URL': 'https://api.example.com/data'
  },
  body: JSON.stringify({ key: 'value' })
});

const data = await response.json();`,
  Python: `import requests

response = requests.post(
  'https://reliapi.kikuai.dev/api/proxy',
  headers={'X-Target-URL': 'https://api.example.com/data'},
  json={'key': 'value'}
)
data = response.json()`,
}
</script>

// app/products/reliapi/page.tsx
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { ArrowLeft, ArrowRight, RefreshCw, Database, Shield } from "lucide-react"

export default function ReliAPIPage() {
  return (
    <div className="noise-bg grid-bg min-h-screen">
      {/* Header */}
      <div className="border-b border-border/40 bg-background/50 backdrop-blur-sm">
        <div className="mx-auto flex max-w-5xl items-center justify-between px-6 py-4">
          <Link
            href="/"
            className="flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors"
          >
            <ArrowLeft className="h-4 w-4" />
            Back
          </Link>
          <Button asChild size="sm" className="rounded-xl bg-primary text-primary-foreground hover:bg-primary/90">
            <Link href="/products/reliapi/demo">Try Demo</Link>
          </Button>
        </div>
      </div>

      {/* Hero */}
      <div className="mx-auto max-w-5xl px-6 py-16">
        <div className="mb-12 text-center">
          <div className="mx-auto mb-6 flex h-16 w-16 items-center justify-center rounded-2xl bg-primary/10 border border-primary/20">
            <RefreshCw className="h-8 w-8 text-primary" />
          </div>
          <h1 className="mb-4 text-4xl font-semibold tracking-tight">ReliAPI</h1>
          <p className="mx-auto max-w-2xl text-lg text-muted-foreground">
            Reliability layer for AI APIs. Automatic retries, caching, and fallbacks. Never lose a request to rate
            limits or downtime again.
          </p>
        </div>

        {/* Visual Demo */}
        <div className="mb-16 rounded-2xl border border-border/60 bg-card/30 p-8">
          <div className="flex items-center justify-center gap-8">
            {/* Input */}
            <div className="flex-1 rounded-xl border border-border/40 bg-background/50 p-6">
              <p className="mb-4 text-xs font-medium uppercase tracking-wider text-muted-foreground">Request</p>
              <div className="space-y-2 font-mono text-xs">
                <div className="rounded bg-muted/30 px-3 py-2 border border-border/30">POST /v1/chat/completions</div>
                <div className="rounded bg-red-500/10 px-3 py-2 border border-red-500/30 text-red-400">
                  429 Rate Limited
                </div>
              </div>
            </div>

            <ArrowRight className="h-6 w-6 text-primary flex-shrink-0" />

            {/* Output */}
            <div className="flex-1 rounded-xl border border-border/40 bg-background/50 p-6">
              <p className="mb-4 text-xs font-medium uppercase tracking-wider text-muted-foreground">
                ReliAPI Response
              </p>
              <div className="space-y-2 font-mono text-xs">
                <div className="rounded bg-primary/10 px-3 py-2 border border-primary/30 text-primary">CACHE HIT ✓</div>
                <div className="rounded bg-muted/30 px-3 py-2 border border-border/30">200 OK (from cache)</div>
                <div className="text-muted-foreground mt-2">Latency: 12ms</div>
              </div>
            </div>
          </div>
        </div>

        {/* Features */}
        <div className="grid gap-6 md:grid-cols-3 mb-16">
          {[
            { icon: RefreshCw, title: "Smart Retries", desc: "Exponential backoff with jitter" },
            { icon: Database, title: "Response Cache", desc: "Semantic caching for identical prompts" },
            { icon: Shield, title: "Fallback Chains", desc: "Automatic failover to backup providers" },
          ].map((feature) => (
            <div key={feature.title} className="rounded-xl border border-border/40 bg-card/20 p-6">
              <feature.icon className="mb-3 h-5 w-5 text-primary" />
              <h3 className="mb-2 font-medium">{feature.title}</h3>
              <p className="text-sm text-muted-foreground">{feature.desc}</p>
            </div>
          ))}
        </div>

        {/* Pricing */}
        <div className="rounded-2xl border border-border/60 bg-card/30 p-8 text-center">
          <h2 className="mb-2 text-xl font-semibold">Pricing</h2>
          <p className="mb-6 text-muted-foreground">Percentage of proxied costs</p>
          <div className="inline-flex items-baseline gap-1">
            <span className="text-4xl font-bold text-primary">1%</span>
            <span className="text-muted-foreground">of API spend</span>
          </div>
          <p className="mt-4 text-sm text-muted-foreground">Minimum $5/month, cache hits are free</p>
          <Button asChild className="mt-6 rounded-xl bg-primary text-primary-foreground hover:bg-primary/90">
            <Link href="/products/reliapi/demo">Get Started</Link>
          </Button>
        </div>

        {/* Docs Link */}
        <div className="mt-8 text-center">
          <Link href="/docs/reliapi" className="text-sm text-muted-foreground hover:text-primary transition-colors">
            Read the documentation →
          </Link>
        </div>
      </div>
    </div>
  )
}
