// app/refund/page.tsx
"use client"

import { motion } from "framer-motion"
import { Navbar } from "@/components/navbar"
import { Footer } from "@/components/footer"

export default function RefundPage() {
  return (
    <div className="relative min-h-screen bg-background text-foreground">
      <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-primary/5 via-transparent to-transparent" />
      <div
        className="pointer-events-none absolute inset-0 opacity-[0.015]"
        style={{
          backgroundImage: `url("data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noise'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noise)'/%3E%3C/svg%3E")`,
        }}
      />

      <Navbar />

      <main className="relative z-10 mx-auto max-w-3xl px-6 py-24">
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5 }}>
          <p className="mb-4 text-sm text-muted-foreground">Last updated: December 2024</p>
          <h1 className="mb-8 text-4xl font-semibold tracking-tight">Refund Policy</h1>

          <div className="space-y-6 text-muted-foreground">
            <section>
              <h2 className="mb-3 text-lg font-medium text-foreground">Overview</h2>
              <p>
                KikuAI offers usage-based pricing with top-up balance. Once purchased, balance is non-refundable as it
                is immediately available for use. However, we understand that situations may arise.
              </p>
            </section>

            <section>
              <h2 className="mb-3 text-lg font-medium text-foreground">Eligibility</h2>
              <p>Refunds may be considered within 7 days of purchase if:</p>
              <ul className="mt-2 list-inside list-disc space-y-1">
                <li>No balance has been used from the purchased top-up</li>
                <li>There was a technical issue preventing access to services</li>
                <li>Duplicate charges occurred due to payment processing errors</li>
              </ul>
            </section>

            <section>
              <h2 className="mb-3 text-lg font-medium text-foreground">How to Request</h2>
              <p>
                Contact us at{" "}
                <a href="mailto:support@kikuai.dev" className="text-primary hover:underline">
                  support@kikuai.dev
                </a>{" "}
                with your account email and purchase details. We typically respond within 2 business days.
              </p>
            </section>

            <section>
              <h2 className="mb-3 text-lg font-medium text-foreground">Processing</h2>
              <p>
                Approved refunds are processed within 5-10 business days. The refund will be credited to the original
                payment method.
              </p>
            </section>
          </div>
        </motion.div>
      </main>

      <Footer />
    </div>
  )
}

// nuxt/pages/refund.vue
<template>
  <div class="noise-bg grid-bg min-h-screen">
    <Navbar />
    <main class="relative z-10 mx-auto max-w-3xl px-6 py-16">
      <PageHeader>
        <template #title>>> REFUND POLICY</template>
        <template #description>
          Last updated: December 25, 2025
        </template>
      </PageHeader>

      <div class="space-y-8 text-muted-foreground">
        <section>
          <h2 class="mb-4 text-lg font-semibold text-foreground">Prepaid Balance</h2>
          <p>
            KikuAI operates on a prepaid balance model. Once you purchase credits, they are added to your account and can be used across all KikuAI APIs.
          </p>
        </section>

        <section>
          <h2 class="mb-4 text-lg font-semibold text-foreground">Refund Eligibility</h2>
          <ul class="list-inside list-disc space-y-2">
            <li>Refunds are available within 14 days of purchase</li>
            <li>Only unused balance is eligible for refund</li>
            <li>Processing fees may apply depending on payment method</li>
          </ul>
        </section>

        <section>
          <h2 class="mb-4 text-lg font-semibold text-foreground">How to Request a Refund</h2>
          <p class="mb-4">
            To request a refund, please contact us at:
          </p>
          <a href="mailto:support@kikuai.dev" class="text-primary hover:underline">
            support@kikuai.dev
          </a>
        </section>

        <section>
          <h2 class="mb-4 text-lg font-semibold text-foreground">Processing Time</h2>
          <p>
            Refunds are typically processed within 5-10 business days after approval. The actual time for funds to appear in your account depends on your payment provider.
          </p>
        </section>

        <section>
          <h2 class="mb-4 text-lg font-semibold text-foreground">Exceptions</h2>
          <p>
            Refunds may be denied in cases of abuse, fraud, or violation of our Terms of Service.
          </p>
        </section>
      </div>
    </main>
    <Footer />
  </div>
</template>
