// app/products/patas/page.tsx
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { ArrowLeft, ArrowRight, MessageSquare, Shield, Brain, Sparkles } from "lucide-react"

export default function PATASPage() {
  return (
    <div className="noise-bg grid-bg min-h-screen">
      {/* Header */}
      <div className="border-b border-border/40 bg-background/50 backdrop-blur-sm">
        <div className="mx-auto flex max-w-5xl items-center justify-between px-6 py-4">
          <Link
            href="/"
            className="flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors"
          >
            <ArrowLeft className="h-4 w-4" />
            Back
          </Link>
          <Button asChild size="sm" className="rounded-xl bg-primary text-primary-foreground hover:bg-primary/90">
            <Link href="/products/patas/demo">Try Demo</Link>
          </Button>
        </div>
      </div>

      {/* Hero */}
      <div className="mx-auto max-w-5xl px-6 py-16">
        <div className="mb-12 text-center">
          <div className="mx-auto mb-6 flex h-16 w-16 items-center justify-center rounded-2xl bg-primary/10 border border-primary/20">
            <MessageSquare className="h-8 w-8 text-primary" />
          </div>
          <h1 className="mb-4 text-4xl font-semibold tracking-tight">Logs → Rules</h1>
          <p className="mx-auto max-w-2xl text-lg text-muted-foreground">
            Upload chat logs or message datasets and get AI-generated spam detection rules. PATAS clusters patterns and
            outputs JSON blocking rules ready for production.
          </p>
        </div>

        {/* Visual Demo */}
        <div className="mb-16 rounded-2xl border border-border/60 bg-card/30 p-8">
          <div className="flex items-center justify-center gap-8">
            {/* Input: Logs */}
            <div className="flex-1 rounded-xl border border-border/40 bg-background/50 p-6">
              <p className="mb-4 text-xs font-medium uppercase tracking-wider text-muted-foreground">Input</p>
              <div className="space-y-2 font-mono text-xs">
                <div className="rounded bg-muted/30 px-3 py-2 border-l-2 border-yellow-500/50">
                  <span className="text-yellow-500">[WARN]</span> Free V-Bucks click here...
                </div>
                <div className="rounded bg-muted/30 px-3 py-2 border-l-2 border-red-500/50">
                  <span className="text-red-500">[SPAM]</span> Get rich quick scheme!!!
                </div>
                <div className="rounded bg-muted/30 px-3 py-2 border-l-2 border-muted-foreground/30">
                  <span className="text-muted-foreground">[INFO]</span> Normal user message
                </div>
                <div className="rounded bg-muted/30 px-3 py-2 border-l-2 border-red-500/50">
                  <span className="text-red-500">[SPAM]</span> Buy followers now!!!
                </div>
              </div>
              <p className="mt-3 text-xs text-muted-foreground text-center">chat_logs.jsonl</p>
            </div>

            <ArrowRight className="h-6 w-6 text-primary flex-shrink-0" />

            {/* Output: JSON Rules */}
            <div className="flex-1 rounded-xl border border-border/40 bg-background/50 p-6">
              <p className="mb-4 text-xs font-medium uppercase tracking-wider text-muted-foreground">Output</p>
              <pre className="rounded-lg bg-muted/30 p-4 text-xs font-mono border border-border/30 overflow-hidden">
                {`{
  "action": "BLOCK",
  "pattern": "free.*v-?bucks",
  "confidence": 0.94,
  "cluster": "gaming_scam"
}`}
              </pre>
              <p className="mt-3 text-xs text-muted-foreground text-center">rules.json</p>
            </div>
          </div>
        </div>

        {/* Features */}
        <div className="grid gap-6 md:grid-cols-3 mb-16">
          {[
            { icon: Brain, title: "AI Clustering", desc: "Automatically groups similar spam patterns" },
            { icon: Shield, title: "Production Ready", desc: "Export rules compatible with Discord, Slack, etc." },
            { icon: Sparkles, title: "Auto-tune", desc: "Suggests SAFE_AUTO or REVIEW_ONLY modes" },
          ].map((feature) => (
            <div key={feature.title} className="rounded-xl border border-border/40 bg-card/20 p-6">
              <feature.icon className="mb-3 h-5 w-5 text-primary" />
              <h3 className="mb-2 font-medium">{feature.title}</h3>
              <p className="text-sm text-muted-foreground">{feature.desc}</p>
            </div>
          ))}
        </div>

        {/* Pricing */}
        <div className="rounded-2xl border border-border/60 bg-card/30 p-8 text-center">
          <h2 className="mb-2 text-xl font-semibold">Pricing</h2>
          <p className="mb-6 text-muted-foreground">Pay per analysis batch</p>
          <div className="inline-flex items-baseline gap-1">
            <span className="text-4xl font-bold text-primary">$0.10</span>
            <span className="text-muted-foreground">/ 1000 messages</span>
          </div>
          <p className="mt-4 text-sm text-muted-foreground">Minimum 100 messages per batch</p>
          <Button asChild className="mt-6 rounded-xl bg-primary text-primary-foreground hover:bg-primary/90">
            <Link href="/products/patas/demo">Analyze Logs</Link>
          </Button>
        </div>

        {/* Docs Link */}
        <div className="mt-8 text-center">
          <Link href="/docs/patas" className="text-sm text-muted-foreground hover:text-primary transition-colors">
            Read the documentation →
          </Link>
        </div>
      </div>
    </div>
  )
}

// nuxt/pages/products/patas.vue
<template>
  <div class="noise-bg grid-bg min-h-screen">
    <Navbar />
    <main class="relative z-10 mx-auto max-w-4xl px-6 py-16">
      <PageHeader back-link="/">
        <template #title>PATAS</template>
        <template #description>
          Pattern-adaptive anti-spam system with semantic discovery
        </template>
      </PageHeader>

      <!-- Action buttons -->
      <div class="mb-12 flex flex-wrap gap-3">
        <a
          href="https://patas.app/demo"
          target="_blank"
          class="inline-flex h-10 items-center justify-center rounded-xl bg-primary px-5 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90"
        >
          Try demo
        </a>
        <NuxtLink
          to="/dashboard"
          class="inline-flex h-10 items-center justify-center rounded-xl border border-border bg-card px-5 text-sm font-medium transition-colors hover:bg-secondary"
        >
          Get API key
        </NuxtLink>
        <a
          href="https://github.com/kiku-jw/PATAS/wiki"
          target="_blank"
          class="inline-flex h-10 items-center justify-center rounded-xl border border-border bg-card px-5 text-sm font-medium transition-colors hover:bg-secondary"
        >
          Docs
        </a>
        <a
          href="https://github.com/kiku-jw/PATAS"
          target="_blank"
          class="inline-flex h-10 items-center gap-2 justify-center rounded-xl border border-border bg-card px-5 text-sm font-medium transition-colors hover:bg-secondary"
        >
          <Github class="h-4 w-4" />
          GitHub
        </a>
        <NuxtLink
          to="/products/patas/batch"
          class="inline-flex h-10 items-center justify-center rounded-xl border border-border bg-card px-5 text-sm font-medium transition-colors hover:bg-secondary"
        >
          Batch Analysis
        </NuxtLink>
      </div>

      <!-- Description -->
      <div class="mb-12 space-y-4 text-muted-foreground">
        <p>
          PATAS (Pattern-Adaptive Transmodal Anti-Spam) is a semantic pattern discovery and rule management engine for large-scale anti-spam operations.
        </p>
        <p>
          It moves beyond simple keyword matching to discover sophisticated spam patterns using semantic clustering and AI-driven analysis.
        </p>
      </div>

      <!-- Problem / When to use -->
      <div class="mb-12 grid gap-6 md:grid-cols-2">
        <div class="rounded-xl border border-border/60 bg-card p-6">
          <h3 class="mb-3 font-semibold">Problem</h3>
          <p class="text-sm text-muted-foreground">
            Spam evolves faster than static rules. Manually creating rules for millions of messages is impossible for human moderators.
          </p>
        </div>
        <div class="rounded-xl border border-border/60 bg-card p-6">
          <h3 class="mb-3 font-semibold">When to use</h3>
          <p class="text-sm text-muted-foreground">
            Use PATAS when you need to protect large-scale communication platforms from bots and spam attacks. It automatically discovers new patterns.
          </p>
        </div>
      </div>

      <div class="mb-12 rounded-xl border border-border/60 bg-card p-6">
        <h3 class="mb-4 font-semibold">Input / Output</h3>
        <div class="grid gap-4 sm:grid-cols-2">
          <div>
            <div class="mb-2 text-xs font-medium uppercase tracking-wider text-muted-foreground">Input</div>
            <p class="text-sm">Raw message logs and user reports</p>
          </div>
          <div>
            <div class="mb-2 text-xs font-medium uppercase tracking-wider text-muted-foreground">Output</div>
            <p class="text-sm">Discovered spam patterns, generated SQL/JSON rules, and effectiveness metrics</p>
          </div>
        </div>
      </div>

      <!-- Demo Section -->
      <section id="demo" class="scroll-mt-24">
        <h2 class="mb-6 text-xl font-semibold">Try it now</h2>
        <CodeBlock
          :tabs="['cURL', 'JavaScript', 'Python']"
          :code="codeExamples"
        />
      </section>
    </main>
    <Footer />
  </div>
</template>

<script setup lang="ts">
import { Github } from 'lucide-vue-next'

const codeExamples = {
  cURL: `curl -X POST https://kikuai.dev/api/demo/patas \\
  -H "Content-Type: application/json" \\
  -d '{"input": "your data here"}'`,
  JavaScript: `const response = await fetch('https://kikuai.dev/api/demo/patas', {
  method: 'POST',
  headers: { 'Content-Type': 'application/json' },
  body: JSON.stringify({ input: 'your data here' })
});

const data = await response.json();`,
  Python: `import requests

response = requests.post(
  'https://kikuai.dev/api/demo/patas',
  json={'input': 'your data here'}
)
data = response.json()`,
}
</script>
