// app/docs/reliapi/page.tsx
import Link from "next/link"
import { ArrowLeft, RefreshCw } from "lucide-react"

export default function ReliAPIDocsPage() {
  return (
    <div className="noise-bg grid-bg min-h-screen">
      {/* Header */}
      <div className="border-b border-border/40 bg-background/50 backdrop-blur-sm">
        <div className="mx-auto flex max-w-4xl items-center justify-between px-6 py-4">
          <Link
            href="/docs"
            className="flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors"
          >
            <ArrowLeft className="h-4 w-4" />
            Back to Docs
          </Link>
        </div>
      </div>

      <div className="mx-auto max-w-4xl px-6 py-16">
        <div className="mb-8 flex items-center gap-4">
          <div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-primary/10 border border-primary/20">
            <RefreshCw className="h-6 w-6 text-primary" />
          </div>
          <div>
            <h1 className="text-2xl font-semibold">ReliAPI</h1>
            <p className="text-muted-foreground">Reliability layer for AI API calls</p>
          </div>
        </div>

        {/* How it works */}
        <section className="mb-12">
          <h2 className="mb-4 text-lg font-semibold">How It Works</h2>
          <p className="mb-4 text-muted-foreground">Replace your OpenAI/Anthropic base URL with ReliAPI:</p>
          <pre className="rounded-xl border border-border/40 bg-background/50 p-4 font-mono text-sm overflow-x-auto">
            {`// Before
const client = new OpenAI({ baseURL: "https://api.openai.com/v1" })

// After
const client = new OpenAI({ 
  baseURL: "https://api.kikuai.dev/v1/reliapi/proxy/openai"
})`}
          </pre>
        </section>

        {/* Features */}
        <section className="mb-12">
          <h2 className="mb-4 text-lg font-semibold">Features</h2>
          <div className="space-y-4">
            <div className="rounded-xl border border-border/40 bg-card/20 p-4">
              <p className="font-medium">Smart Retries</p>
              <p className="mt-1 text-sm text-muted-foreground">
                Automatic retry with exponential backoff on 429/5xx errors.
              </p>
            </div>
            <div className="rounded-xl border border-border/40 bg-card/20 p-4">
              <p className="font-medium">Semantic Caching</p>
              <p className="mt-1 text-sm text-muted-foreground">Cache identical prompts to reduce latency and costs.</p>
            </div>
            <div className="rounded-xl border border-border/40 bg-card/20 p-4">
              <p className="font-medium">Fallback Chains</p>
              <p className="mt-1 text-sm text-muted-foreground">
                Automatically failover to backup providers on errors.
              </p>
            </div>
          </div>
        </section>

        {/* Configuration */}
        <section className="mb-12">
          <h2 className="mb-4 text-lg font-semibold">Configuration</h2>
          <pre className="rounded-xl border border-border/40 bg-background/50 p-4 font-mono text-sm overflow-x-auto">
            {`// Headers for configuration
X-ReliAPI-Cache: true          // Enable caching
X-ReliAPI-Cache-TTL: 3600      // Cache TTL in seconds
X-ReliAPI-Retries: 3           // Max retry attempts
X-ReliAPI-Fallback: anthropic  // Fallback provider`}
          </pre>
        </section>

        {/* Pricing */}
        <section className="rounded-2xl border border-border/60 bg-card/30 p-6">
          <h2 className="mb-2 text-lg font-semibold">Pricing</h2>
          <p className="text-muted-foreground">1% of proxied API costs. Minimum $5/month. Cache hits are free.</p>
        </section>
      </div>
    </div>
  )
}

// nuxt/pages/products/reliapi.vue
<template>
  <div class="noise-bg grid-bg min-h-screen">
    <Navbar />
    <main class="relative z-10 mx-auto max-w-4xl px-6 py-16">
      <PageHeader back-link="/">
        <template #title>ReliAPI</template>
        <template #description>
          Reliability layer for API calls with retries, caching, and circuit breakers
        </template>
      </PageHeader>

      <!-- Action buttons -->
      <div class="mb-12 flex flex-wrap gap-3">
        <NuxtLink
          to="#demo"
          class="inline-flex h-10 items-center justify-center rounded-xl bg-primary px-5 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90"
        >
          Try demo
        </NuxtLink>
        <NuxtLink
          to="/dashboard"
          class="inline-flex h-10 items-center justify-center rounded-xl border border-border bg-card px-5 text-sm font-medium transition-colors hover:bg-secondary"
        >
          Get API key
        </NuxtLink>
        <a
          href="https://github.com/KikuAI-Lab/reliapi/wiki"
          target="_blank"
          class="inline-flex h-10 items-center justify-center rounded-xl border border-border bg-card px-5 text-sm font-medium transition-colors hover:bg-secondary"
        >
          Docs
        </a>
        <a
          href="https://github.com/KikuAI-Lab/reliapi"
          target="_blank"
          class="inline-flex h-10 items-center gap-2 justify-center rounded-xl border border-border bg-card px-5 text-sm font-medium transition-colors hover:bg-secondary"
        >
          <Github class="h-4 w-4" />
          GitHub
        </a>
      </div>

      <!-- Description -->
      <div class="mb-12 space-y-4 text-muted-foreground">
        <p>
          ReliAPI provides automatic retries, response caching, deduplication, and circuit-breaker logic for any HTTP API endpoint.
        </p>
        <p>
          It handles transient failures, reduces load on downstream services, and improves response times through intelligent caching and request deduplication.
        </p>
      </div>

      <!-- Problem / When to use -->
      <div class="mb-12 grid gap-6 md:grid-cols-2">
        <div class="rounded-xl border border-border/60 bg-card p-6">
          <h3 class="mb-3 font-semibold">Problem</h3>
          <p class="text-sm text-muted-foreground">
            External APIs can be unreliable, slow, or rate-limited. Without proper handling, failures cascade and performance degrades.
          </p>
        </div>
        <div class="rounded-xl border border-border/60 bg-card p-6">
          <h3 class="mb-3 font-semibold">When to use</h3>
          <p class="text-sm text-muted-foreground">
            Use ReliAPI when calling external APIs that may be unreliable, slow, or rate-limited. It handles all the retry and caching logic automatically.
          </p>
        </div>
      </div>

      <div class="mb-12 rounded-xl border border-border/60 bg-card p-6">
        <h3 class="mb-4 font-semibold">Input / Output</h3>
        <div class="grid gap-4 sm:grid-cols-2">
          <div>
            <div class="mb-2 text-xs font-medium uppercase tracking-wider text-muted-foreground">Input</div>
            <p class="text-sm">HTTP request to any API endpoint</p>
          </div>
          <div>
            <div class="mb-2 text-xs font-medium uppercase tracking-wider text-muted-foreground">Output</div>
            <p class="text-sm">Cached response if available, or retried request with circuit breaker protection</p>
          </div>
        </div>
      </div>

      <!-- Visual Demo -->
      <div class="mb-12 rounded-xl border border-border/60 bg-card p-6">
        <h3 class="mb-4 font-semibold">How it works</h3>
        <div class="flex flex-wrap items-center gap-4 font-mono text-sm">
          <div class="rounded-lg bg-secondary/50 px-4 py-2">
            <span class="text-muted-foreground">GET /api/data</span>
          </div>
          <ArrowRight class="h-5 w-5 text-primary" />
          <div class="rounded-lg bg-emerald-500/10 px-4 py-2">
            <span class="text-emerald-400">CACHE HIT</span>
            <span class="ml-2 text-muted-foreground/60">2ms</span>
          </div>
        </div>
      </div>

      <!-- Demo Section -->
      <section id="demo" class="scroll-mt-24">
        <h2 class="mb-6 text-xl font-semibold">Try it now</h2>
        <CodeBlock
          :tabs="['cURL', 'JavaScript', 'Python']"
          :code="codeExamples"
        />
      </section>
    </main>
    <Footer />
  </div>
</template>

<script setup lang="ts">
import { Github, ArrowRight } from 'lucide-vue-next'

const codeExamples = {
  cURL: `curl -X POST https://reliapi.kikuai.dev/api/proxy \\
  -H "Content-Type: application/json" \\
  -H "X-Target-URL: https://api.example.com/data" \\
  -d '{"key": "value"}'`,
  JavaScript: `const response = await fetch('https://reliapi.kikuai.dev/api/proxy', {
  method: 'POST',
  headers: {
    'Content-Type': 'application/json',
    'X-Target-URL': 'https://api.example.com/data'
  },
  body: JSON.stringify({ key: 'value' })
});

const data = await response.json();`,
  Python: `import requests

response = requests.post(
  'https://reliapi.kikuai.dev/api/proxy',
  headers={'X-Target-URL': 'https://api.example.com/data'},
  json={'key': 'value'}
)
data = response.json()`,
}
</script>
